### ISSUE TITLE
Examples in ReadMe

### ISSUE THREAD

**Issue by thenitai** [vkarpov15/connect-mongodb-session#12]
Hi there,

Like your lib. Thank you.

However, I've had some issues getting this up and running with your examples. Eventually here is what I got it running with:

```
var session = require('express-session');
var MongoDBStore = require('connect-mongodb-session')(session);
```

**Comment by vkarpov15** [comment]
Yep that's the correct way to do it. I suppose the examples don't make it entirely clear that you need to require() in connect-mongodb-session and then call it with express-session. The examples assume that `var connectMongoDB = require('connect-mongodb-session')`. I'll improve that, thanks for the suggestion.
