### ISSUE TITLE
hash _id using hashed indexes

### ISSUE THREAD

**Issue by christkv** [vkarpov15/connect-mongodb-session#6]
http://docs.mongodb.org/manual/tutorial/create-a-hashed-index/

this is to ensure as random as possible id's to make sure writes in sharded systems are evenly distributed.

**Comment by vkarpov15** [comment]
@christkv I'd argue that this is something that should be done outside of this module. Managing indexes in a module is a little dangerous IMO, if user really wants a hashed index they can just create it in the shell. What's the benefit to managing it in this module?
